version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    networks:
      - task-management
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
          - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - task-management
    depends_on:
      - postgres


  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      RABBITMQ_DEFAULT_USER: rab
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq￼
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - task-management



networks:
  task-management:
    driver: bridge

volumes:
  postgres_data:
    driver: local