eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
server:
  port: 8084
spring:
  application:
    name: companies-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/company
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: task-client
            client-secret: GRnfhjeldW0UhTo0R22M8qi3gGxzYOXt
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/auth/realms/task-realm
            user-name-attribute: preferred_username
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/task-realm
          jwk-set-uri: http://keycloak:8080/auth/realms/task-realm/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      principal-attribute: sub
      resource-id: task-client