spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
server:
  port: 8081
