spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/task
  application:
    name: task-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: task-client
            client-secret: GRnfhjeldW0UhTo0R22M8qi3gGxzYOXt
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/auth/realms/task-realm
            user-name-attribute: preferred_username
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/task-realm
          jwk-set-uri: http://keycloak:8080/auth/realms/task-realm/protocol/openid-connect/certs
  rabbitmq:
    host: localhost
    username: root
    password: root
    port: 5672
    my-queue:
      name: taskQueue
    exchange:
      name: taskExchange
    virtual-host: vhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

jwt:
  auth:
    converter:
      principal-attribute: sub
      resource-id: task-client
service:
  project:
    name: project-service
    path: /api/v1/project
  user:
    name: user-service
    path: /api/v1/user

resilience4j:
  circuitbreaker:
    instances:
      project:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

server:
  port: 8082
