spring:
  application:
    name: project-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/project
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: task-client
            client-secret: GRnfhjeldW0UhTo0R22M8qi3gGxzYOXt
            scope: openid, profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/auth/realms/task-realm
            user-name-attribute: preferred_username
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/task-realm
          jwk-set-uri: http://keycloak:8080/auth/realms/task-realm/protocol/openid-connect/certs
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

jwt:
  auth:
    converter:
      principal-attribute: sub
      resource-id: task-client

service:
  company:
    name: company-service
    path: /api/v1/company

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        ignoreExceptions:
          - org.example.projectservice.exception.NotFoundException
    instances:
      company:
        baseConfig: default
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        ignoreExceptions:
          - org.example.projectservice.exception.NotFoundException


server:
  port: 8083

